[package]
name = "rs_aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
num = "0.4.1"
petgraph = "0.6.4"
regex = "1.10.2"
rgb = "0.8.37"
